# Generated by Django 4.2.5 on 2023-10-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
    ]
